from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(SubDistrict),
admin.site.register(District),
admin.site.register(Neighbor),
admin.site.register(SubNeighbor),
admin.site.register(PlotNo),
admin.site.register(identification),
admin.site.register(Purchaseinfo),
admin.site.register(Landtype),
admin.site.register(Notary),
admin.site.register(Parcel),
admin.site.register(PropertyMap),
admin.site.register (Plotmap),
admin.site.register(Dhaxalayaal),
admin.site.register(DhaxalSubDoc),
admin.site.register(SupportingDOC),
admin.site.register(BussinessRegistration),
admin.site.register(BussinessRegistrator),
admin.site.register(BussinessStatus),
admin.site.register(Coordinates),
admin.site.register(KalawarejinSubDoc),
admin.site.register(PropertyRevenu),
admin.site.register(BussinessRevenu),
admin.site.register(Charges),
admin.site.register(Currencies),
admin.site.register(ChagreType),