# Generated by Django 3.2.8 on 2021-11-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20211116_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinfo',
            name='identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.identification'),
        ),
    ]
