# Generated by Django 3.2.8 on 2021-11-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_purchaseinfo_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhaxalayaal',
            name='RegistrationNO',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='identification',
            name='RegistrationNO',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='Registrationid',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='sellerinfo',
            name='RegistrationNO',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='supportingdoc',
            name='RegistrationNO',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
