# Generated by Django 3.2.8 on 2021-11-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20211118_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dhaxalsubdoc',
            old_name='Parcel',
            new_name='RegistrationNO',
        ),
    ]
