# Generated by Django 3.2.8 on 2021-11-20 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0030_rename_parcel_dhaxalsubdoc_registrationno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdistrict',
            old_name='District',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='subneighbor',
            old_name='Neigbour',
            new_name='neigbour',
        ),
        migrations.AddField(
            model_name='district',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
